// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_flexSCReg 22
#define SYS_flexSCWait 23
#define SYS_flexScFork 24
#define SYS_flexScExit 25
#define SYS_flexWait 26
#define SYS_flexScPipe 27
#define SYS_flexScRead 28
#define SYS_flexScKill 29
#define SYS_flexScExec 30
#define SYS_flexScFstat 31
#define SYS_flexScChdir 32
#define SYS_flexScDup   33
#define SYS_flexScGetpid 34
#define SYS_flexScSbrk   35
#define SYS_flexScSleep  36
#define SYS_flexScUptime 37
#define SYS_flexScOpen   38
#define SYS_flexScWrite  39
#define SYS_flexScMknod  40
#define SYS_flexScUnlink 41
#define SYS_flexScLink   42
#define SYS_flexScMkdir  43
#define SYS_flexScClose  44

